/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface StencilButton {
    }
    interface StencilIcon {
    }
}
declare global {
    interface HTMLStencilButtonElement extends Components.StencilButton, HTMLStencilElement {
    }
    var HTMLStencilButtonElement: {
        prototype: HTMLStencilButtonElement;
        new (): HTMLStencilButtonElement;
    };
    interface HTMLStencilIconElement extends Components.StencilIcon, HTMLStencilElement {
    }
    var HTMLStencilIconElement: {
        prototype: HTMLStencilIconElement;
        new (): HTMLStencilIconElement;
    };
    interface HTMLElementTagNameMap {
        "stencil-button": HTMLStencilButtonElement;
        "stencil-icon": HTMLStencilIconElement;
    }
}
declare namespace LocalJSX {
    interface StencilButton {
    }
    interface StencilIcon {
    }
    interface IntrinsicElements {
        "stencil-button": StencilButton;
        "stencil-icon": StencilIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "stencil-button": LocalJSX.StencilButton & JSXBase.HTMLAttributes<HTMLStencilButtonElement>;
            "stencil-icon": LocalJSX.StencilIcon & JSXBase.HTMLAttributes<HTMLStencilIconElement>;
        }
    }
}
